swagger: '2.0'
info:
  title: hcOS Swagger API Documentation
  version: 1.0.0
apis:
  - url: 'http://api.hcos.upmce.net/v2/api-docs'
    paths:
      base: '/neutrino'
  - url: 'http://petstore.swagger.io/v2/swagger.json'
    paths:
      base: '/pets'